apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcore-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netcore-demo
  template:
    metadata:
      labels:
        app: netcore-demo
    spec:
      containers:
      - name: netcore-demo
        image: ashwilliams/netcore-upload:latest
        ports:
        - containerPort: 80
        env:
        - name: GitHub
          value: "https://github.com/AshWilliams/NetCoreUpload" 